<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup>
    <IncludePath>$(VC_IncludePath);$(WindowsSDK_IncludePath);$(SolutionDir)Third Party\assimp\include;$(SolutionDir)Third Party\assimp\out\build\x64-$(Configuration)\include</IncludePath>
    <LibraryPath>$(VC_LibraryPath_x64);$(WindowsSDK_LibraryPath_x64);$(SolutionDir)Third Party\assimp\out\build\x64-$(Configuration)\lib</LibraryPath>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <WarningLevel>Level3</WarningLevel>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <MultiProcessorCompilation>true</MultiProcessorCompilation>
      <AdditionalIncludeDirectories>$(SolutionDir)Third Party\enet\include;$(SolutionDir)Third Party\GLFW;$(SolutionDir)Third Party\glm;$(SolutionDir)Third Party\imgui;$(SolutionDir)Third Party\soloud\include</AdditionalIncludeDirectories>
      <SDLCheck>true</SDLCheck>
      <IntrinsicFunctions>true</IntrinsicFunctions>
      <PreprocessorDefinitions>_UNICODE;UNICODE;_CONSOLE;%(PreprocessorDefinitions);WITH_WINMM</PreprocessorDefinitions>
      <FunctionLevelLinking>true</FunctionLevelLinking>
      <LanguageStandard>stdcpp20</LanguageStandard>
      <LanguageStandard_C>stdc17</LanguageStandard_C>
      <ConformanceMode>true</ConformanceMode>
    </ClCompile>
    <Link>
      <AdditionalDependencies>Ws2_32.lib;$(CoreLibraryDependencies);%(AdditionalDependencies);$(SolutionDir)Third Party\GLFW\glfw3.lib;enet64.lib;winmm.lib;$(SolutionDir)Third Party\assimp\out\build\x64-Release\lib\assimp-vc143-mt.lib</AdditionalDependencies>
      <AdditionalLibraryDirectories>$(SolutionDir)Third Party\GLFW;$(SolutionDir)Third Party\enet</AdditionalLibraryDirectories>
      <SubSystem>Console</SubSystem>
      <GenerateDebugInformation>true</GenerateDebugInformation>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>