
layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

//! #include "gpuPixelRep.glsl"

// TODO: Should these be constants instead
uniform int gridCols;
uniform int gridRows;

layout(std430, binding = 4) buffer PixelsRead
{
	Pixel read[];
};

layout(std430, binding = 5) buffer PixelsWrite
{
	Pixel write[];
};

int indexFromCoords(ivec2 coord)
{
	return (coord.x % gridCols) + (coord.y * gridCols);
}

ivec2 coordsFromIndex(int index)
{
	return ivec2(index % gridCols, index / gridCols);
}
