
//! #include "basePixel.comp"

vec2 getExternalForcesAt(ivec2 coords)
{
//	ivec2 middle = ivec2(512, 512);
//	vec2 toMiddle = middle - coords;
//	return normalize(toMiddle) * 0.00005;
	return vec2(0, -0.0002);
}

void main() {
	ivec2 coords = getLocalCoords();
	int index = indexFromCoords(coords);

	Pixel pixel = getRead(index);
	
	if (!pixel.movedLastUpdate)
	{
		pixel.subPos += pixel.vel;
//		pixel.colour.r = 0.1;
	}
	else
	{
//		pixel.colour.r = 0.9;
	}
	float subPosLength = length(pixel.subPos);
	float subPosLimit = 0.49;
	if (subPosLength >= subPosLimit)
	{
		pixel.subPos /= subPosLength;
		pixel.subPos *= subPosLimit;
	}

	// need to ensure speed limit here
	if (pixel.matID == 2)
	{
		float speedLimit = 1.0;
		vec2 newVel = pixel.vel + getExternalForcesAt(coords);
		float newVelLength = length(newVel);
		if (newVelLength > speedLimit)
		{
			newVel /= newVelLength;
			newVel *= speedLimit;
		}
		pixel.vel = newVel;
	}

	pixel.movedLastUpdate = false;

	setWrite(index, pixel);
	setRead(index, pixel);
}
