#version 460 core


layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

//! #include "gpuPixelRep.glsl"

// TODO: Should these be constants instead
uniform int gridCols;
uniform int gridRows;

layout(std430, binding = 4) buffer PixelsRead
{
	Pixel read[];
};

layout(std430, binding = 5) buffer PixelsWrite
{
	Pixel write[];
};

int indexFromCoords(ivec2 coord)
{
	return (coord.x % gridCols) + (coord.y * gridCols);
}

ivec2 coordsFromIndex(int index)
{
	return ivec2(index % gridCols, index / gridCols);
}

uniform int frameCount;

// We don't actually want to work out exactly the position if we don't care, only need for the one that will take our spot
ivec2 getExpectedPos(ivec2 coords, int index, bool evenFrame)
{
	if (read[index].matID == 2)
	{
		return coords + ivec2(round(read[index].vel + read[index].subPos));
	}

	// Not expected to move
	return coords;
}

vec2 getExternalForcesAt(ivec2 coords)
{
	return vec2(0.0, -0.01);
}

bool UpdateCell(ivec2 coords, int index)
{
	Pixel at = read[index];

	bool even1Frame = frameCount % 2 == 0;
	bool even2Frame = frameCount % 4 < 2;
	bool even4Frame = frameCount % 8 < 4;
	
	// is a square but yeah
	int searchRadius = 1;

	int searchStartX = even2Frame ? -searchRadius : searchRadius;
	int searchEndX   = even2Frame ? searchRadius + 1 : -searchRadius - 1;
	int searchDirX   = even2Frame ? 1 : -1;
	
	int searchStartY = even4Frame ? -searchRadius : searchRadius;
	int searchEndY   = even4Frame ? searchRadius + 1 : -searchRadius - 1;
	int searchDirY   = even4Frame ? 1 : -1;

	if (at.matID != 1)
	{
		return false;
	}
	for (int ly = searchStartY; ly != searchEndY; ly+=searchDirY)
	{
		for (int lx = searchStartX; lx != searchEndX; lx+=searchDirX)
		{
			if (ly == lx && lx == 0)
			{
				// This is our pixel, dont check would just fail
				continue;
			}
			ivec2 lCoords = coords + ivec2(lx, ly);
			int lIndex = indexFromCoords(lCoords);

			if (getExpectedPos(lCoords, lIndex, even1Frame) == coords)
			{
				write[index] = read[lIndex];
				write[lIndex] = at;
				return true;
			}
		}
	}
	return false;
}

void main() {

	ivec2 coords = ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y);
	int index = indexFromCoords(coords);
	UpdateCell(coords, index);
	// need to ensure speed limit here
	float speedLimit = 1.0;
	vec2 newVel = write[index].vel + getExternalForcesAt(coords);
	float newVelLength = length(newVel);
	if (newVelLength > speedLimit)
	{
		newVel /= newVelLength;
		newVel *= speedLimit;
	}
	write[index].vel = newVel;
}
