#version 460 core

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

//! #include "basePixel.comp"

//! #include "colourUtils.glsl"


uniform vec2 currentInput;

struct PlayerInfo
{
	vec2 pos;
	vec2 vel;
	uint colour;
};

layout(std430, binding = 2) buffer PlayerSlot
{
	PlayerInfo playerInfo;
};

vec2 getGravityForPlayer(PlayerInfo playerInfo)
{
	return vec2(0, -0.0001);
}

const float moveSpeed = 1.1;

void main() {
	vec2 oldPlayerPos = playerInfo.pos;
	playerInfo.vel += getGravityForPlayer(playerInfo);
	playerInfo.pos += moveSpeed * currentInput;
	playerInfo.pos += playerInfo.vel;

	ivec2 globalCoords = ivec2(floor(playerInfo.pos.x), floor(playerInfo.pos.y));
	ivec2 localCoords = globalToLocalCoords(globalCoords);
	ivec2 chunkDir = getLocalChunkDirection(localCoords);
	// Need to check what chunk we are moving to
	// Would usually be outselves, followed by a direct neighbor, and then diagonally

	DoChunkCheckThing(0, chunkData2);
	DoChunkCheckThing(1, chunkData3);
	DoChunkCheckThing(2, chunkData4);
	DoChunkCheckThing(3, chunkData5);
	DoChunkCheckThing(4, chunkData6);
	DoChunkCheckThing(5, chunkData7);
	DoChunkCheckThing(6, chunkData8);
	DoChunkCheckThing(7, chunkData9);

	Pixel pixelAt = getReadFromGlobalCoords(globalCoords);
	playerInfo.colour = colourPackUnsigned(vec4(playerInfo.pos.x / gridCols, playerInfo.pos.y / gridRows, (pixelAt.matID == 0) ? 1 : 0, 1));

	if (!matsEmptyStatus[pixelAt.matID])
	{
		playerInfo.vel = vec2(0, 0);
		playerInfo.pos = oldPlayerPos;
	}


//	ivec2 coords = ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y);
//	int index = indexFromCoords(coords);
//
//	write[index] = read[index];
//	write[index].colour = vec4(1, 1, 0, 1);
}
